### ISSUE TITLE
Waiting for operation to finish with callback

### ISSUE THREAD

**Issue by shubham0704** [shubham0704/tutor.ai#3]
It seems that making post synchronous has not yet resolved the issue. Also the requests are queued up. It would be nice if we could have just the graph_builder function synchronous. 
For reference  check  [here](synchronous).

**Comment by shubham0704** [comment]
This is in reference to this [commit](https://github.com/shubham0704/tutor.ai/commit/90bd124bb804378458c646c9e414ece3507cdf10)

**Comment by Souldiv** [comment]
Problem was with the class Graphbuilder fixed in this [commit](https://github.com/shubham0704/ai_tutor/commit/dfc9ae7c588ff57102f1e6b7b6326fb012ea3d47) to ai_tutor.
